# Generated by Django 5.1.4 on 2025-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150)),
                ('rm', models.CharField(blank=True, max_length=20, null=True)),
                ('ra', models.CharField(blank=True, max_length=20, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('cpf', models.CharField(blank=True, max_length=30, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MT', 'MT'), ('MS', 'MS'), ('MG', 'MG'), ('PA', 'PA'), ('PB', 'PB'), ('PR', 'PR'), ('PE', 'PE'), ('PI', 'PI'), ('RJ', 'RJ'), ('RN', 'RN'), ('RS', 'RS'), ('RO', 'RO'), ('RR', 'RR'), ('SC', 'SC'), ('SP', 'SP'), ('SE', 'SE'), ('TO', 'TO')], max_length=2, null=True)),
                ('cor_raca', models.CharField(blank=True, max_length=30, null=True)),
                ('sexo', models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino')], max_length=10, null=True)),
                ('necessita_educacao_especial', models.BooleanField(default=False)),
                ('nis', models.CharField(blank=True, max_length=80, null=True)),
                ('responsavel_1', models.CharField(blank=True, max_length=150, null=True)),
                ('contato_1', models.CharField(blank=True, max_length=30, null=True)),
                ('responsavel_2', models.CharField(blank=True, max_length=150, null=True)),
                ('contato_2', models.CharField(blank=True, max_length=30, null=True)),
                ('outros_contatos', models.CharField(blank=True, max_length=255, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('medicamento', models.BooleanField(default=False)),
                ('qual_medicamento', models.CharField(blank=True, max_length=255, null=True)),
                ('diabete', models.BooleanField(default=False)),
                ('alergia', models.BooleanField(default=False)),
                ('cardiaco', models.BooleanField(default=False)),
                ('mora_com_os_pais', models.BooleanField(default=True)),
                ('motivo_mora_com_os_pais', models.CharField(blank=True, max_length=255, null=True)),
                ('neuro', models.BooleanField(default=False)),
                ('motivo_neuro', models.CharField(blank=True, max_length=255, null=True)),
                ('psicologo', models.BooleanField(default=False)),
                ('motivo_psicologo', models.CharField(blank=True, max_length=255, null=True)),
                ('fono', models.BooleanField(default=False)),
                ('motivo_fono', models.CharField(blank=True, max_length=255, null=True)),
                ('integral', models.BooleanField(default=False)),
                ('transporte', models.CharField(choices=[('onibus', 'Onibus'), ('van', 'Van'), ('indefinido', 'Indefinido')], default='indefinido', max_length=20)),
                ('obs_transporte', models.CharField(blank=True, max_length=255, null=True)),
                ('retirada_aluno', models.CharField(blank=True, max_length=255, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('nome', models.CharField(max_length=150)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('matricula', models.CharField(blank=True, max_length=30, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('funcao', models.CharField(blank=True, max_length=150, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('nome', models.CharField(max_length=10)),
                ('ano', models.IntegerField(default=2025)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
