# Generated by Django 5.2.5 on 2025-09-06 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_remove_aluno_acao_remove_aluno_info_remove_aluno_ip_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professor',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disciplina', to='cadastros.disciplina'),
        ),
    ]
