# Generated by Django 5.2.5 on 2025-10-02 13:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_professor_disciplina'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('matricula', models.CharField(blank=True, max_length=30, null=True)),
                ('rg', models.CharField(blank=True, max_length=20, null=True)),
                ('nascimento', models.DateField(blank=True, null=True)),
                ('telefone', models.CharField(blank=True, max_length=30, null=True)),
                ('funcao', models.CharField(blank=True, max_length=150, null=True)),
                ('endereco', models.CharField(blank=True, max_length=200, null=True)),
                ('observacoes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
