# Generated by Django 5.2.5 on 2025-10-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_funcionario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sala',
            old_name='nome',
            new_name='classe',
        ),
        migrations.AddField(
            model_name='sala',
            name='serie',
            field=models.CharField(default='1', max_length=10),
            preserve_default=False,
        ),
    ]
