# Generated by Django 5.2.5 on 2025-10-02 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_rename_nome_sala_classe_sala_serie'),
    ]

    operations = [
        migrations.AddField(
            model_name='sala',
            name='periodo',
            field=models.CharField(default='manha', max_length=10),
            preserve_default=False,
        ),
    ]
