# Generated by Django 5.2.5 on 2025-10-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0007_sala_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sala',
            name='classe',
            field=models.CharField(choices=[('1', 'A'), ('2', 'B'), ('3', 'C'), ('4', 'D')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='sala',
            name='periodo',
            field=models.CharField(choices=[('1', 'Manhã'), ('2', 'Tarde')], default='1', max_length=10),
        ),
        migrations.AlterField(
            model_name='sala',
            name='serie',
            field=models.CharField(choices=[('1', '1º'), ('2', '2º'), ('3', '3º'), ('4', '4º'), ('5', '5º')], default='1', max_length=10),
        ),
    ]
