# Generated by Django 5.1.4 on 2025-08-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('acao', models.TextField(blank=True, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='info',
        ),
        migrations.RemoveField(
            model_name='sistema',
            name='ip',
        ),
    ]
