# Generated by Django 5.1.4 on 2025-08-31 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auditoria_remove_sistema_acao_remove_sistema_info_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sistema',
            name='cabecalho',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
        migrations.AlterField(
            model_name='sistema',
            name='rodape',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/'),
        ),
    ]
