# Generated by Django 5.2.5 on 2025-09-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_sistema_cabecalho_alter_sistema_logo_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sistema',
            old_name='cabecalho',
            new_name='logo_educacao',
        ),
        migrations.RenameField(
            model_name='sistema',
            old_name='rodape',
            new_name='logo_municipio',
        ),
    ]
