# Generated by Django 5.2.5 on 2025-09-26 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_cabecalho_sistema_logo_educacao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sistema',
            name='nova_conta',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sistema',
            name='redefinir_senha',
            field=models.BooleanField(default=False),
        ),
    ]
