# Generated by Django 5.1.4 on 2025-08-27 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Avisos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('ip', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True)),
                ('mensagem', models.TextField(blank=True, null=True)),
                ('envio', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('matricula', 'Matrícula'), ('remanejamento', 'Remanejamento'), ('transferencia', 'Transferência'), ('outros', 'Outros')], default='Matrícula', max_length=30)),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('enviado', 'Enviado'), ('erro', 'Erro')], default='Pendente', max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
