# Generated by Django 5.1.4 on 2025-08-27 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('avisos', '0001_initial'),
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='avisos',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.professor'),
        ),
    ]
