# Generated by Django 5.1.4 on 2025-08-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('avisos', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avisos',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='avisos',
            name='info',
        ),
        migrations.RemoveField(
            model_name='avisos',
            name='ip',
        ),
    ]
