# Generated by Django 5.1.4 on 2025-08-31 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atribuicaoprofessor',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='atribuicaoprofessor',
            name='info',
        ),
        migrations.RemoveField(
            model_name='atribuicaoprofessor',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='frequenciaprofessores',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='frequenciaprofessores',
            name='info',
        ),
        migrations.RemoveField(
            model_name='frequenciaprofessores',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='movimentacoes',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='movimentacoes',
            name='info',
        ),
        migrations.RemoveField(
            model_name='movimentacoes',
            name='ip',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='acao',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='info',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='ip',
        ),
    ]
