# Generated by Django 5.2.5 on 2025-09-06 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0002_remove_atribuicaoprofessor_acao_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atribuicaoprofessor',
            name='disciplina',
        ),
        migrations.RemoveField(
            model_name='turma',
            name='numero',
        ),
    ]
