# Generated by Django 5.2.5 on 2025-09-07 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0003_remove_atribuicaoprofessor_disciplina_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movimentacoes',
            name='destino',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='origem',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
