# Generated by Django 5.2.5 on 2025-09-08 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0004_alter_movimentacoes_destino_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movimentacoes',
            name='ano',
        ),
        migrations.AddField(
            model_name='movimentacoes',
            name='data',
            field=models.DateField(blank=True, null=True),
        ),
    ]
