# Generated by Django 5.2.5 on 2025-09-08 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0005_remove_movimentacoes_ano_movimentacoes_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='turma',
            name='numero_aluno',
            field=models.IntegerField(default=0),
        ),
    ]
