# Generated by Django 5.2.5 on 2025-09-09 20:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_professor_disciplina'),
        ('movimentacoes', '0006_turma_numero_aluno'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimentacoes',
            name='destino_input',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='movimentacoes',
            name='origem_input',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='destino', to='cadastros.sala'),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origem', to='cadastros.sala'),
        ),
    ]
