# Generated by Django 5.2.5 on 2025-09-18 11:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_professor_disciplina'),
        ('movimentacoes', '0007_movimentacoes_destino_input_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaprofessores',
            name='período',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='turma',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='cadastros.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turmas', to='cadastros.sala'),
        ),
    ]
