# Generated by Django 5.2.5 on 2025-09-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0008_frequenciaprofessores_período_alter_turma_aluno_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='frequenciaprofessores',
            old_name='período',
            new_name='periodo',
        ),
    ]
