# Generated by Django 5.2.5 on 2025-09-18 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0009_rename_período_frequenciaprofessores_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='frequenciaprofessores',
            name='tipo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
