# Generated by Django 5.2.5 on 2025-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0010_frequenciaprofessores_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequenciaprofessores',
            name='data',
        ),
        migrations.AddField(
            model_name='frequenciaprofessores',
            name='data_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='frequenciaprofessores',
            name='data_inicial',
            field=models.DateField(blank=True, null=True),
        ),
    ]
