# Generated by Django 5.2.5 on 2025-10-02 16:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_funcionario'),
        ('movimentacoes', '0011_remove_frequenciaprofessores_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrequenciaFuncionarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('criado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('atualizado_por', models.CharField(blank=True, max_length=100, null=True)),
                ('data_inicial', models.DateField(blank=True, null=True)),
                ('data_final', models.DateField(blank=True, null=True)),
                ('quantidade', models.IntegerField(default=5)),
                ('tipo', models.CharField(blank=True, max_length=50, null=True)),
                ('funcionario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastros.funcionario')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
