# Generated by Django 5.2.5 on 2025-10-02 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacoes', '0012_frequenciafuncionarios'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='frequenciafuncionarios',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='frequenciafuncionarios',
            name='periodo',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
