# Generated by Django 5.2.5 on 2025-10-10 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_sala_classe_alter_sala_periodo_and_more'),
        ('movimentacoes', '0013_remove_frequenciafuncionarios_quantidade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribuicaoprofessor',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicao', to='cadastros.professor'),
        ),
        migrations.AlterField(
            model_name='atribuicaoprofessor',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.sala'),
        ),
        migrations.AlterField(
            model_name='frequenciafuncionarios',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.funcionario'),
        ),
        migrations.AlterField(
            model_name='frequenciaprofessores',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.professor'),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastros.aluno'),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destino', to='cadastros.sala'),
        ),
        migrations.AlterField(
            model_name='movimentacoes',
            name='origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origem', to='cadastros.sala'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cadastros.aluno'),
        ),
        migrations.AlterField(
            model_name='turma',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='turmas', to='cadastros.sala'),
        ),
    ]
