# Generated by Django 5.2.5 on 2025-10-10 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0008_alter_sala_classe_alter_sala_periodo_and_more'),
        ('movimentacoes', '0014_alter_atribuicaoprofessor_professor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atribuicaoprofessor',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes', to='cadastros.professor'),
        ),
    ]
